version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: employme-app
    restart: unless-stopped
    volumes:
      - ./storage:/var/www/html/storage
      - ./storage/logs:/var/www/html/storage/logs
    environment:
      - APP_ENV=production
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=employme
      - DB_USERNAME=postgres
      - DB_PASSWORD=secret
    depends_on:
      - db
    networks:
      - employme-network

  db:
    image: postgres:15-alpine
    container_name: employme-db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=employme
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    networks:
      - employme-network

networks:
  employme-network:
    driver: bridge

volumes:
  postgres_data:
